#!/bin/sh

NODM_BIN=/sbin/nodm

case "$1" in
    start)
        printf "Starting NODM: "
        $NODM_BIN
        echo "done"
        ;;
    stop)
        echo "Stopping NODM"
        killall -q nodm
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
